# Generated by Django 4.2.7 on 2023-12-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating_field',
            field=models.IntegerField(choices=[(1, '    *    '), (2, '   * *   '), (3, '  * * *  '), (4, ' * * * * '), (5, '* * * * *')], null=True),
        ),
    ]
