# Generated by Django 4.2.7 on 2023-12-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_rating_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rated_by',
            field=models.JSONField(default=dict),
        ),
    ]
