# Generated by Django 4.2.7 on 2023-11-27 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_navigation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navigation',
        ),
    ]
