# Generated by Django 4.2.7 on 2023-12-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(default=models.DateTimeField(auto_now=True)),
        ),
    ]
