# Generated by Django 4.2.7 on 2023-12-25 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_spoiler',
        ),
        migrations.AlterField(
            model_name='message',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='forum.discussion'),
        ),
    ]
