# Generated by Django 4.2.7 on 2023-12-25 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_message_is_spoiler_alter_message_discussion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='created_at_time',
        ),
    ]
