# Generated by Django 4.2.7 on 2023-12-25 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_rename_created_at_time_message_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='created_at_time',
        ),
    ]
