# Generated by Django 4.2.7 on 2023-12-26 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0006_rename_created_at_time_message_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='genre',
            field=models.CharField(choices=[('Hobby', 'Hobby'), ('Flood', 'Flood'), ('Book', 'Book'), ('Competition', 'Competition')], max_length=255),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to=settings.AUTH_USER_MODEL),
        ),
    ]
