# Generated by Django 4.2.7 on 2023-12-26 01:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0007_alter_discussion_genre_alter_discussion_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='user',
        ),
        migrations.AddField(
            model_name='discussion',
            name='user',
            field=models.ManyToManyField(related_name='discussions', to=settings.AUTH_USER_MODEL),
        ),
    ]
