# Generated by Django 4.2.7 on 2023-12-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='justuser',
            name='avatar',
            field=models.ImageField(blank=True, default='https://lemmy.world/pictrs/image/f9b045ca-ca15-43b4-aeed-1188183d7087.png', null=True, upload_to='static/users/avatars/'),
        ),
    ]
