# Generated by Django 4.2.7 on 2023-11-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justuser',
            name='about_yourself',
        ),
        migrations.RemoveField(
            model_name='justuser',
            name='occupation',
        ),
    ]
