# Generated by Django 4.2.7 on 2023-12-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_justuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justuser',
            name='username',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
